    const productList = [
      {
        image: "/src/assets/watch2.png",
        price: 1200,
        name: "Rolex",
        id: 1,
        quantity: 1,
        count: 1,
      },
      {
        image: "src/assets/laptop.png",
        price: 800,
        name: "HP",
        id: 2,
        quantity: 1,
        count: 1,
      },
      {
        image: "src/assets/watch1.png",
        price: 2000,
        name: "Rolex",
        count: 1,
        id: 3,
        quantity: 1,
      },
      {
        image: "src/assets/men12.png",
        count: 1,
        price: 200,
        name: "Bently",
        id: 4,
        quantity: 1,
      },
      {
        image: "src/assets/thumbnail (3).png25.png",
        count: 1,
        price: 6000,
        name: "Kawasaki",
        id: 5,
        quantity: 1,
      },
      {
        image: "src/assets/thumbnail (3).png24.png",
        price: 4000,
        count: 1,
        name: "Honda",
        id: 6,
        quantity: 1,
      },
      {
        image: "src/assets/thumbnail (3).png32.png",
        price: 40,
        count: 1,
        name: "Masuri",
        id: 7,
        quantity: 1,
      },
      {
        image:"src/assets/thumbnail (3).png23.png",
        price: 4000,
        count: 1,
        name: "HONDA",
        id: 8,
        quantity: 1,
      },
    ];
export default productList;